'''
    ---------------------------------------------------------------------------
    OpenCap processing: example_kinetics_local.py
    ---------------------------------------------------------------------------
    Copyright 2022 Stanford University and the Authors

    Author(s): Antoine Falisse, Scott Uhlrich
    Adapted for local opencap-core results.

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy
    of the License at http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    This script is the same workflow as example_kinetics.py, but it uses
    results that already exist locally. This is useful when a session was
    reprocessed with opencap-core and you do not have write permission for the
    online OpenCap session.

    Expected local folder structure:
        localSessionDir/sessionMetadata.yaml
        localSessionDir/OpenSimData/Kinematics/<trial_name>.mot
        localSessionDir/OpenSimData/Model/<OpenSimModel>_scaled.osim

    The dynamic simulation results will be written locally under:
        localSessionDir/OpenSimData/Dynamics

    Please contact us for any questions: https://www.opencap.ai/#contact
'''

# %% Directories, paths, and imports. You should not need to change anything.
import os
import sys

baseDir = os.path.dirname(os.path.abspath(__file__))
opensimADDir = os.path.join(baseDir, 'UtilsDynamicSimulations', 'OpenSimAD')
if baseDir not in sys.path:
    sys.path.append(baseDir)
if opensimADDir not in sys.path:
    sys.path.append(opensimADDir)

from UtilsDynamicSimulations.OpenSimAD.utilsOpenSimAD import processInputsOpenSimAD, plotResultsOpenSimAD
from UtilsDynamicSimulations.OpenSimAD.mainOpenSimAD import run_tracking

# %% User inputs.
'''
Please provide:

    localSessionDir:
                    Path to the local session folder generated by opencap-core.
                    This folder should contain sessionMetadata.yaml and
                    OpenSimData.

    trial_name:     Name of the trial you want to simulate. The script expects
                    to find:
                    localSessionDir/OpenSimData/Kinematics/<trial_name>.mot

    motion_type:    Type of activity you want to simulate. Options are
                    'running', 'walking', 'drop_jump', 'sit_to_stand',
                    'squats', 'jumping', and 'other'.

    time_window:    Time interval you want to simulate. It is recommended to
                    simulate trials shorter than 2s. Set to [] to simulate the
                    full trial. For 'squats' or 'sit_to_stand', you can instead
                    provide repetition below.

    repetition:     Only if motion_type is 'sit_to_stand' or 'squats'. This is
                    the index of the repetition you want to simulate, where 0 is
                    the first repetition. Set to None if you use time_window.

    case:           String appended to result file names.

    treadmill_speed:
                    Optional treadmill speed in m/s. Use 0 for overground.

    contact_side:   Foot/feet with contact spheres. Options are 'all', 'left',
                    and 'right'.
'''

# Path to your local opencap-core session results.
localDataFolder = r'C:\Users\wagnerel85475\Documents\opencap-core\Data'
localSessionDir = os.path.join(localDataFolder,
                               '23d52d41-69fe-47cf-8b60-838e4268dd50')

# Select the trial and simulation settings.
trial_name = '00b62adc-ceca-4ff1-a1f0-2b688e0f28db'
motion_type = 'walking'
time_window = [3.2, 4.7]
repetition = None
case = 'local'
treadmill_speed = 0
contact_side = 'all'

# Set to True to solve the optimal control problem.
solveProblem = True
# Set to True to analyze the results of the optimal control problem. If you
# solved the problem already, and only want to analyze/process the results, you
# can set solveProblem to False and run this script with analyzeResults set to
# True. This is useful if you do additional post-processing but do not want to
# re-run the problem.
analyzeResults = True

# Set to True to plot results.
plotResults = True

# %% Setup.
# Infer dataFolder and session_id from the local session folder. The OpenSimAD
# functions expect the same Data/<session_id> layout as example_kinetics.py.
localSessionDir = os.path.abspath(localSessionDir)
dataFolder = os.path.dirname(localSessionDir)
session_id = os.path.basename(localSessionDir)

pathMetadata = os.path.join(localSessionDir, 'sessionMetadata.yaml')
pathKinematics = os.path.join(localSessionDir, 'OpenSimData', 'Kinematics',
                              trial_name + '.mot')
pathModelFolder = os.path.join(localSessionDir, 'OpenSimData', 'Model')

if not os.path.exists(pathMetadata):
    raise FileNotFoundError('Missing local metadata file: ' + pathMetadata)
if not os.path.exists(pathKinematics):
    raise FileNotFoundError('Missing local kinematics file: ' + pathKinematics)
if not os.path.exists(pathModelFolder):
    raise FileNotFoundError('Missing local model folder: ' + pathModelFolder)

settings = processInputsOpenSimAD(baseDir, dataFolder, session_id, trial_name,
                                  motion_type, time_window, repetition,
                                  treadmill_speed, contact_side,
                                  overwrite=False)

# %% Simulation.
run_tracking(baseDir, dataFolder, session_id, settings, case=case,
             solveProblem=solveProblem, analyzeResults=analyzeResults)

# %% Plots.
# To compare different cases, add to the cases list, eg cases=['local','1'].
if plotResults:
    plotResultsOpenSimAD(dataFolder, session_id, trial_name, settings,
                         cases=[case])
